# Generated by Django 3.2.9 on 2021-12-04 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mift', '0002_alter_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.date(2021, 12, 4)),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_date',
            field=models.DateField(),
        ),
    ]
