# Generated by Django 3.2.9 on 2021-11-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ifsc',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
